import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import styles from "../styles/Home.module.scss";

const Home: NextPage = () => {
  const { push } = useRouter();

  function handleSetFilters(from: string, to: string) {
    push({
      pathname: "/search/",
      query: {
        from,
        to,
      },
    });
  }

  function handleSubmit(e: React.SyntheticEvent) {
    e.preventDefault();
    const target = e.target as typeof e.target & {
      from: { value: string };
      to: { value: string };
    };
    const from = target.from.value;
    const to = target.to.value;

    handleSetFilters(from, to);
  }
  return (
    <div className={styles.home}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicons/favicon.ico" />
      </Head>

      <main className={styles.home}>
        <div className={styles.onboarding}>
          <form className={styles.form} onSubmit={handleSubmit}>
            <label className={styles.label}>
              <div>From</div>
              <input className={styles.input} name="from" type="date" />
            </label>
            <label className={styles.label}>
              <div>To</div>
              <input className={styles.input} name="to" type="date" />
            </label>
            <button type="submit">Search</button>
          </form>
        </div>
      </main>
    </div>
  );
};

export default Home;
